spring:
  h2:
    console:
      enabled: true

  datasource:
#    url: jdbc:h2:mem:travel-testDB
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:13306/travelzip-test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
