spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:13306/travelzip-test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


